### ISSUE TITLE
[Improve UI] Can I contribute to it

### ISSUE THREAD

**Issue by jayk-gupta** [VasilenaA/VasilenaA.github.io#2]
You can improve the UI more by adding different fonts, color of fonts and more things.
Can can contribute to your project and improve a few things?

**Comment by VasilenaA** [comment]
What are your ideas?

**Comment by jayk-gupta** [comment]
1. Change colors
2. Change font family
3. Add margin, padding at some places.
What do you say?

**Comment by VasilenaA** [comment]
Colors like in the main page, you mean, or the ones for the text. Оtherwise the 2 and 3 points sound good to me.








 >-------- Оригинално писмо --------

 >От: Jay Kumar Gupta ***@***.***

 >Относно: Re: [VasilenaA/VasilenaA.github.io] [Improve UI] Can I contribute to
 it (Issue #2)

 >До: "VasilenaA/VasilenaA.github.io"  

 >Изпратено на: 20.03.2023 19:16



 
 
  
  
    
    Change colors  
    Change font family  
    Add margin, padding at some places.
 What do you say?
